# Generated by Django 4.0.4 on 2022-06-01 08:19

from django.db import migrations, models
import to_do.models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todonote',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AddField(
            model_name='todonote',
            name='status',
            field=models.IntegerField(choices=[(0, 'Активно'), (1, 'Отложено'), (2, 'Выполнено')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='todonote',
            name='time_point',
            field=models.DateTimeField(blank=True, default=to_do.models.dateTimePoint, verbose_name='Срок выполнения'),
        ),
    ]
